version: '3.3'
services:
    budibase:
        container_name: budibase
        hostname: budibase_host
        ports:
            - '10000:80'
        volumes:
            - '/mnt/user/appdata/bubibase:/data'
            - '/mnt/user/appdata/budibase/database/:/opt/couchdb/data'
        restart: unless-stopped
        image: 'budibase/budibase:latest'