version: '3.3'
services:
    doku:
        container_name: doku
        hostname: doku_host
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/:/hostroot:ro'
        ports:
            - '9090:9090'
        image: amerkurev/doku