---
version: "3.3"
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    container_name: filebrowser
    ports:
      - 8777:80
    hostname: filebrowser_host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '/mnt:/srv'
      - /mnt/disk2/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/disk2/appdata/filebrowser/config/settings.json:/config/settings.json
    restart: unless-stopped
