---
version: "3.3"
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    container_name: filebrowser
    ports:
      - 8777:80
    hostname: filebrowser_host
    environment:
        - PUID=99
        - PGID=100
        - TZ=America/Los_Angeles
    volumes:
      - '/mnt/user:/srv'
      - /mnt/user/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/user/appdata/filebrowser/config/settings.json:/config/settings.json
    restart: unless-stopped
