version: "3.8"

services:
  minecraft:
    container_name: cobblemon
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 8G
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: "0.14.22"
      FABRIC_LAUNCHER_VERSION: "0.11.2"
      VERSION: 1.19.2
      DIFFICULTY: hard
      MOTD: "Pokemon cricosos a 5 peso"
      PVP: "FALSE"
      MAX_PLAYERS: 69
      MODRINTH_PROJECTS: cobblemon
      OPS: "lakakidd"
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    volumes:
      - /home/lakakid/dotfiles/cobblemon:/data
