version: "3.3"
services:

  ddnsgooglejbpixelxyz:
    image: dragoncube/google-domains-ddns
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/jbpixel/Docker/googleddns/configxyz:/config
  
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s