services:
    app:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: nginxpm
      hostname: nginxpm_host
      restart: unless-stopped
      ports:
        - '88:80' #HTTP TRAFFIC
        - '81:81' #DASHBOARD
        - '443:443' #HTTPS TRAFFIC
        # Uncomment the next line if you uncomment anything in the section
      environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
      volumes:
        - /mnt/user/appdata/nginxpm:/data
        - /mnt/user/appdata/nginxpm/letsencrypt:/etc/letsencrypt

