version: '3.7'
services:
  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP=USER=danielcs
      - FPT=PASSWORD=supersecret
    volumes:
      - /mnt/storage/media:/srv
    expose:
      - 21
    network_mode: host