version: '3.7'
services:
  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP_USER=danielcs
      - FTP_PASSWORD=supersecret
    volumes:
      - /media/hdd/movies:/srv
    expose:
      - 21
    network_mode: host