services:
  portainer:
    container_name: portainer
    network_mode: host
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /home/lakakid/dotfiles/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
