version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr_host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

    networks:
      - nginxpm_default
    volumes:
      - /home/jbpixel/Docker/radarr:/config
      - /mnt:/movies #optional
      - /mnt/ntfs2/TMP:/downloads
    restart: unless-stopped
    labels:
        flame.icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/radarr.png
        flame.name: Radarr
        flame.type: app
        flame.url: radarr.jbpixel.xyz
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
networks:  
  nginxpm_default:
    external: true
    name: nginxpm_default