version: "3"
services:
    Sonarr:
      cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
      cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
      container_name: Sonarr
      entrypoint:
        - /init
      environment:
        - PUID=1024
        - PGID=100
        - TZ=PST
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - HOME=/root
        - LANGUAGE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - TERM=xterm
        - XDG_CONFIG_HOME=/config/xdg
        - SONARR_BRANCH=main
      expose:
        - 8989/tcp
      hostname: sonarr_host
      image: linuxserver/sonarr:latest
      ipc: private
      labels:
        flame.icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/sonarr.png
        flame.name: Sonarr
        flame.type: app
        flame.url: sonarr.jbpixel.xyz
      logging:
        driver: json-file
        options: {}
      networks:
        - nginxpm_default
      restart: unless-stopped
      volumes:
        - /home/jbpixel/Docker/sonarr:/config
        - /mnt:/data
networks:  
  nginxpm_default:
    external: true
    name: nginxpm_default