version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: uptimekuma_host
    volumes:
      - ./mnt/user/appdata/uptimekuma:/app/data1
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s