services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex_host
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/disk2/appdata/plex:/config
      - /mnt/disk1/media:/media
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]