version: '3'

services:
  stablediffusion:
    container_name: stablediffusion
    image: sharrnah/stable-diffusion-guitard
    environment:
      - RUN_MODE
      - WEBUI_RELAUNCH=true
      - ENABLE_TEXTUAL_INVERSION
    ports:
      - 7860:8080
    stdin_open: true
    tty: true
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      # mount cache dirs
      - /mnt/user/appdata/stablediffusion:/root/.cache
      - /mnt/user/appdata/stablediffusion/facexlib/:/app/src/facexlib/facexlib/weights/
      - /mnt/user/appdata/stablediffusion/gfpgan/:/app/gfpgan/weights/
      # mounting model files
      - /mnt/user/appdata/stablediffusion/models:/models/
      # generated outputs mount
      - /mnt/user/appdata/stablediffusion/outputs/:/outputs/