version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    hostname: memos
    restart: unless-stopped
    volumes:
      - "/home/lakakid/dotfiles/memos:/memos"
    ports:
      - 5230:5230
