services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/overseerr:/app/config
    restart: unless-stopped
