---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett_host
    networks:  
      - nginxpm-stack_default

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /mnt/disk2/appdata/jackett:/config
      - /mnt/disk2/appdata/jackett/downloads:/downloads
    restart: unless-stopped
networks:
  nginxpm-stack_default:
    external: true
    name: nginxpm-stack_default