services:
  app:
    environment:
      - PUID = 1000
      - PGID = 1000
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    hostname: npm_host
    restart: unless-stopped
    ports:
      - '80:80' #HTTP TRAFFIC
      - '81:81' #DASHBOARD
      - '443:443' #HTTPS TRAFFIC
    volumes:
      - /home/lakakid/dotfiles/nginxpm:/data
      - /home/lakakid/dotfiles/nginxpm/letsencrypt:/etc/letsencrypt
