services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    hostname: npm_host
    restart: unless-stopped
    ports:
      - '88:80' #HTTP TRAFFIC
      - '81:81' #DASHBOARD
      - '443:443' #HTTPS TRAFFIC
    volumes:
      - /mnt/user/appdata/nginxpm:/data
      - /mnt/user/appdata/nginxpm/letsencrypt:/etc/letsencrypt
