services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin_host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl="https://jellyfin.{DOMAIN}" #optional
    volumes:
      - /home/lakakid/jellyfin/config:/config
      - /media/hdd:/media
      - /tmp:/transcode

    ports:
      - 8096:8096
      # - 8920:8920 #optional
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr_host
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /home/lakakid/dotfiles/jellyseer/config:/app/config
    restart: unless-stopped
  
  jfa-go:
    container_name: jfa-go
    hostname: jfa-go_host
    ports:
      - '8056:8056'
      - '8057:8057'
    volumes:
      - '/home/lakakid/dotfiles/jfa-go/config:/data'
      - '/home/lakakid/dotfiles/jfa-go/config:/jf'
      - '/etc/localtime:/etc/localtime:ro'
    image: hrfee/jfa-go
