version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    hostname: jellyfin_host
    container_name: jellyfin
    user: uid:gid
    volumes:
      - /mnt/disk2/appdata/jellyfin:/config
      - /mnt/cache/appdata/jellyfin:/cache
      - /mnt/cache/appdata/jellyfin/transcode:/cache
      - /mnt/disk1/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.jbpixel.xyz`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      # - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.jbpixel.xyz
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
networks:
 traefik_default:
    external: true
    name: traefik_default