services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl="https://jellyfin.jbpixel.xyz" #optional
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/media/:/media
      - /mnt/sata_cache/appdata/jellyfin/transcode:/transcode
      
    ports:
      - 8096:8096
      # - 8920:8920 #optional
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
