services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl="https://jellyfin.jbpixel.xyz" #optional
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/media/:/media
      - /mnt/cache/appdata/jellyfin/transcode:/transcode
    ports:
      - 8096:8096
      # - 8920:8920 #optional
    restart: unless-stopped
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.jbpixel.xyz`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
networks:
  traefik_default:
    external: true
    name: traefik_default