---
version: "2.1"
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jbpixel/Docker/mylar:/config
      - /mnt/ntfs1/COMICS:/comics
      - /mnt/ssddrives/mylardownloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped