version: '3.3'
services:
    adguard:
        image: adguard/adguardhome
        container_name: adguardhome
        restart: unless-stopped
        network_mode: host
        volumes:
            - '/mnt/user/appdata/adguard/work:/opt/adguardhome/work'
            - '/mnt/user/appdata/adguard/opt:/opt/adguardhome/conf'
        ports:
            - '54:54/tcp'
            - '54:54/udp'
            - '67:67/udp'
            - '68:68/udp'
            - '82:80/tcp'
            - '444:443/tcp'
            - '444:443/udp'
            - '3002:3000/tcp'
            - '853:853/tcp'
            - '784:784/udp'
            - '853:853/udp'
            - '8853:8853/udp'
            - '5443:5443/tcp'
            - '5443:5443/udp'