services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin_host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl="https://jellyfin.{DOMAIN}" #optional
    volumes:
      - /home/danielg-h/jellyfin/config:/config
      - /home/media:/media

    ports:
      - 8096:8096
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr_host
    tty:  true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/media/:/media
      - /mnt/user/media/MOVIES/:/movies
      - /mnt/sata_cache/downloads:/downloads
    restart: unless-stopped
    ports:
      - 7878:7878

