version: "3.3"
services:
  minecraft-atm8:
    image: itzg/minecraft-server
    container_name: atm8
    hostname: atm8_host
    ports:
      - 25575:25575
    volumes:
      - "/home/lakakid/dotfiles/mc:/data"
    tty: true
    stdin_open: true
    environment:
      UID: 1000
      GUID: 1000
      ONLINE_MODE: "FALSE"
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "400"
      # USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.19.3
      SEED: 420420420420
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 18
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 14
      OPS: user, lakakidd
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      MODE: survival
      MOTD: "Welcome to cumzone!"
      # INIT_MEMORY: 5G
      MAX_MEMORY: 8G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 2G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s