version: "3.3"
services:
  minecraft-mexicrew:
    image: itzg/minecraft-server
    container_name: minecraft-mexicrew
    restart: unless-stopped
    hostname: minecraftmexicrew_host
    ports:
      - 25567:25567
    networks:
      - nginxpm_default
    volumes:
      - "/mnt/ssddrives/mexicrew:/data"
    tty: true
    stdin_open: true
    environment:
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: 0.14.7
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "400"
      # USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.18.2
      SEED: -6643636733
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 18
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 20
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 6
      MODE: survival
      MOTD: "§c§lFeliz Jueves!... §bOr as I like to call it, §cThursday!"
      INIT_MEMORY: 2G
      MAX_MEMORY: 12G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 6
      ICON: "https://media.forgecdn.net/avatars/556/541/637901678731763596.png"

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  nginxpm_default:
    external: true
    name: nginxpm_default