version: "3.3"
services:
  mc:
    image: itzg/minecraft-server:java19
    container_name: betterforever2
    hostname: betterforever2_host
    network_mode: host
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      FORGE_VERSION: "43.2.4"
      MOTD: "FELIZ JUEVES!"
      DIFFICULTY: "hard"
      OPS: jbpixel_
      MAX_PLAYERS: 12
      ALLOW_NETHER: true
      ENABLE_COMMAND_BLOCK: true
      MAX_TICK_TIME: -1
      VIEW_DISTANCE: 14
      SEED: 6642043478
      MODE: "survival"
      PVP: "true"
      ALLOW_FLIGHT: "TRUE"
      MEMORY: "2.5G"
      TZ: "America/Los_Angeles"
      USE_AIKAR_FLAGS: "true"
      GUI: "FALSE"
      PUID: 99
      PGID: 100
    ports:
      - "25565:25565"
    volumes:
      - /mnt/user/appdata/betterforever2:/data
    stdin_open: true
    tty: true
