services:
    openspeedtest:
        restart: unless-stopped
        container_name: openspeedtest
        hostname: openspeedtest_host
        # ports:
        #     - '3000:3000'
        image: openspeedtest/latest
        networks:
          - nginxpm_default
        labels:
          flame.icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/openspeedtest.png
          flame.name: Open Speed Test
          flame.type: app
          flame.url: ost.jbpixel.xyz
        healthcheck:
          test: ["CMD", "/bin/check-health"]
          interval: 10s
          timeout: 3s
networks:
  nginxpm_default:
    external: true
    name: nginxpm_default