version: '3.3'
services:
    stable-diffusion-webui:
      network_mode: 'host'
      container_name: stable-diffusion-webui
      volumes:
            - '/mnt/user/appdata/stable-diffusion-webui:/mnt/invokeai'
      image: "ubuntu:latest"
      deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]