version: "2.1"
services:
  readarr:
    hostname: readarr_host
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/lakakid/dotfiles/readarr:/config
      - /media/hdd/manga:/manga
      - /media/hdd/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped