version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        hostname: kavita_host
        volumes:
            - /mnt/user/media/COMICS:/COMICS
            - /mnt/user/media/BOOKS:/BOOKS
            - /mnt/user/appdata/kavita:/kavita/config
        environment:
            - TZ=America/Los_Angeles
        ports:
            - "5000:5000"
        restart: unless-stopped
