version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        hostname: kavita_host
        volumes:
            - /mnt/user/comics_share/:/comics 
            - /mnt/user/comics_share/BOOKS/:/books
            - /mnt/user/appdata/kavita:/kavita/config
        environment:
            - TZ=America/Los_Angeles
        ports:
            - "8688:5000"
        restart: unless-stopped
