services:
    Sonarr:
      container_name: Sonarr
      hostname: sonarr_host
      image: linuxserver/sonarr:latest
      restart: unless-stopped
      volumes:
        - /home/lakakid/dotfiles/sonarr:/config
        - /media/hdd/tvshows:/tvshows
        # - /mnt/user/appdata/qbittorrent/downloads:/downloads
        - /media/hdd/downloads:/downloads
      environment:
        - TZ=America/Los_Angeles
      ports:  
        - 8989:8989
