version: "3"
services:
    Sonarr:
      container_name: Sonarr
      hostname: sonarr_host
      image: linuxserver/sonarr:latest
      restart: unless-stopped
      volumes:
        - /mnt/disk2/appdata/sonarr:/config
        - /mnt/disk1/media/SHOWS:/SHOWS
        - /mnt/disk1/media/ANIME:/ANIME
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Los_Angeles
      # ports:  
      #   - 8989:8989
      networks:
        - traefik_default
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.jbpixel.xyz`)"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

# networks:
#   nginxpm-stack_default:
#     external: true
#     name: nginxpm-stack_default
networks:
  traefik_default:
    external: true
    name: traefik_default