version: "3.3"
services:
  minecraft-mexicrew:
    image: itzg/minecraft-server
    container_name: minecraft-mexicrew
    restart: unless-stopped
    hostname: minecraftmexicrew_host
    ports:
      - 25567:25567
    volumes:
      - "/mnt/nvme/containers/Minecraft/mexicrew:/data"
    tty: true
    stdin_open: true
    environment:
      TYPE: CURSEFORGE
      CF_SERVER_MOD: All-of-Fabric-5-Server-1.2.4.zip
      USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.18.2
      SEED: 219774805124124960
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 15
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 14
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 6
      MODE: survival
      MOTD: "verano no significa vacaciones"
      INIT_MEMORY: 2G
      MAX_MEMORY: 12G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 5
