version: "3.3"
services:
  minecraft-mexicrew:
    image: itzg/minecraft-server
    container_name: minecraft-mexicrew
    restart: unless-stopped
    hostname: minecraftmexicrew_host
    ports:
      - 25567:25567
    volumes:
      - "/mnt/ssddrives/mexicrew:/data"
    tty: true
    stdin_open: true
    environment:
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: 0.14.6
      # USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.18.2
      SEED: -6643636733
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 15
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 20
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 6
      MODE: survival
      MOTD: "§c§lFeliz Jueves!... §bOr as I like to call it, §cThursday!"
      INIT_MEMORY: 2G
      MAX_MEMORY: 10G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 6
      ICON: "https://i.redd.it/jbt32ylpcf391.jpg"
