services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr_host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/disk2/appdata/radarr:/config
      - /mnt/disk1/media/:/media
      - /mnt/disk1/media2:/media2
      - /mnt/disk2/appdata/qbittorrent/downloads:/downloads
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.jbpixel.xyz`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

# networks:
#   nginxpm-stack_default:
#     external: true
#     name: nginxpm-stack_default
networks:
  traefik_default:
    external: true
    name: traefik_default