version: '3.3'
services:
    sd-webui:
        ports:
            - '8501:8501'
        environment:
            - STREAMLIT_SERVER_HEADLESS=true
            - WEBUI_SCRIPT=webui_streamlit.py
            - VALIDATE_MODELS=false
        volumes:
            - '/mnt/user/appdata/sygil/outputs:/sd/outputs'
            - '/mnt/user/media_cache/sygil/models:/sd/models'
        image: 'hlky/sd-webui:latest'
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]