---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /mnt/user/appdata/code-server/config:/config
      - projects:/projects
    ports:
      - 8543:8443
      - 4000-4050:3000-3050
    restart: unless-stopped

  volumes:
    projects:
     external: true