---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    hostname: komga_host
    volumes:
      - /mnt/user/comics_share/:/comics 
      - /mnt/user/appdata/komga:/config
      - /mnt/user/comics_share/BOOKS/:/books
    ports:
      - 8585:8000
    user: "nobody:nobody"
    environment:
      - TZ="America/Los_Angeles"
    restart: unless-stopped