version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       hostname: jellyseerr_host
       environment:
            - LOG_LEVEL=debug
            - TZ=America/Los_Angeles
       ports:
            - 5055:5055
       volumes:
            - /mnt/user/appdata/config:/app/config
       restart: unless-stopped