---
version: "3.3"
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    container_name: filebrowser
    hostname: filebrowser_host
    networks:
      - nginxpm_default
    labels:
        flame.icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/filebrowser.png
        flame.name: File Browser
        flame.type: app
        flame.url: files.jbpixel.xyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '/:/srv'
      - $HOME/Docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - $HOME/Docker/filebrowser//filebrowser/config/settings.json:/config/settings.json
    restart: unless-stopped
networks:
  nginxpm_default:
    external: true
    name: nginxpm_default
