---
version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    hostname: filebrowser_host
    networks:
      - nginxpm_default
    # ports:
    #   - '8080:80'
    volumes:
      - /:/data
      - /mnt/nvme/BeMOre-self-hosted-files/Docker/stacks/filebrowser/config:/config
    restart: unless-stopped  
networks:  
  nginxpm_default:
    external: true
    name: nginxpm_default