version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hasbullathegreat
      - MYSQL_PASSWORD=hasbullathegreat
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nginxpm_default

  app:
    image: nextcloud
    restart: always
    hostname: nextcloud_host
    #ports:
    #  - 8080:80
    networks:
      - nginxpm_default
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=hasbullathegreat
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      flame.icon: https://github.com/walkxhub/dashboard-icons/blob/master/png/nextcloud.png?raw=true
      flame.name: Nextcloud
      flame.type: app
      flame.url: nextcloud.{DOMAIN}
networks:  
  nginxpm_default:
    external: true
    name: nginxpm_default