services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
        - PUID=99
        - PGID=100
        - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/user/media:/media
    ports:
      - 8123:8123 #optional

    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hass.rule=Host(`hass.jbpixel.xyz`)"
      - "traefik.http.routers.hass.entrypoints=websecure"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
      - "traefik.http.routers.hass.service=hass"
      - "traefik.http.routers.hass.tls.certresolver=myresolver"