services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
        - PUID=99
        - PGID=100
        - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/user/media:/media
    ports:
      - 8123:8123 #optional
    devices:
      - /path/to/device:/path/to/device #optional
    restart: unless-stopped