version: "3"
services:
  actual_server:
    container_name: actual_server
    image: jlongster/actual-server
    hostname: actual_host
    networks:
      - nginxpm_default
    # ports:
    #   - "5006:5006"
    volumes:
      - '/home/jbpixel/Docker/actual/data:/data'


    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped
networks:  
  nginxpm_default:
    external: true
    name: nginxpm_default
