version: "3"
services:
  actual_server:
    container_name: actual_server
    image: jlongster/actual-server

    ports:
      - "5006:5006"
    volumes:
      - '/home/jbpixel/Docker/actual/data:/data'
    restart: unless-stopped