services:
    rss:
        image: ghcr.io/ssddanbrown/rss:latest
        container_name: rss
        hostname: rss_host
        environment:
            - APP_NAME=RSS
            - APP_FEED_UPDATE_FREQUENCY=15
            - APP_LOAD_POST_THUMBNAILS=true
        volumes:
            - /mnt/user/appdata/rss-files:/app/storage
        ports:
            - "8093:80"
        restart: unless-stopped