services:
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    hostname: tachidesk_host
    container_name: tachidesk
    networks:
      - nginxpm_default
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
networks:
  nginxpm_default:
    attachable: true
    name: nginxpm_default
