version: "3.3"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft_host
    ports:
      - 25565:25565
    volumes:
      - "/home/lakakid/dotfiles/mine:/data"
    environment:  
      ONLINE_MODE: "FALSE"
      VERSION: 1.20
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 18
      MAX_WORLD_SIZE: 300000
      ALLOW_NETHER: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      VIEW_DISTANCE: 14
      SIMULATION_DISTANCE: 8
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
 