version: "3.3"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft_host
    ports:
      - 25565:25565
    volumes:
      - "/home/lakakid/dotfiles/mine:/data"
    environment:
      ONLINE_MODE: "FALSE"
      MAX_TICK_TIME: -1
      # USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.19.3
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 18
      MAX_WORLD_SIZE: 300000
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 14
      OPS: lakakidd
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      MODE: survival
      MOTD: "Welcome to cumzone!"
      # INIT_MEMORY: 5G
      MAX_MEMORY: 8G
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 2G
 